# Generated by Django 4.0.4 on 2022-05-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('Student', 'student'), ('Assistant', 'assistant'), ('Teacher', 'teacher')]),
        ),
    ]
