# Generated by Django 4.0.4 on 2022-05-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outro', '0003_customuser_alter_answer_user_alter_chatmembers_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mail',
        ),
    ]
