# Generated by Django 4.0.4 on 2022-05-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outro', '0004_remove_customuser_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
